apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: atlas-m10-aws
  namespace: atlas
spec:
  serviceClassExternalName: mongodb-atlas-aws
  servicePlanExternalName: M10
  parameters:
    cluster:
      mongoDBMajorVersion: "4.2"      
      providerSettings:
        regionName: US_WEST_2
