apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: atlas-m10-azure
  namespace: atlas
spec:
  serviceClassExternalName: mongodb-atlas-azure
  servicePlanExternalName: M10
  parameters:
    cluster:
      providerSettings:
        regionName: US_EAST_2
