# Deployment to run the service broker.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-osb
  namespace: atlas
  labels:
    app: atlas-osb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-osb
  template:
    metadata:
      labels:
        app: atlas-osb
    spec:
      containers:
        - name: osb
          image: quay.io/mongodb/mongodb-atlas-service-broker:latest
          ports:
            - containerPort: 4000
          env:
            - name: BROKER_HOST
              value: "0.0.0.0"

---
# Service to expose the service broker inside the cluster.
apiVersion: v1
kind: Service
metadata:
  name: atlas-osb
  namespace: atlas
  labels:
    app: atlas-osb
spec:
  selector:
    # Will match pods deployed by the "osb" deployment.
    app: atlas-osb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
